[package]
name = "vex"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.98"
console_error_panic_hook = "0.1.7"
serde = "1.0.219"
serde_json = "1.0.142"
wasm-bindgen = "0.2"
web-sys = "0.3.77"
